version: '3'
services:
  sass-client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - sass-client
